.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH BIGFOOT 1 "May 2007" Dust "User Manuals"
.de cB
.ps -2
.ft CB
.in 7
.nf
..
.de cE
.fi
.in  
.ft
.ps
..
.SH NAME
bigfoot
.SH DESCRIPTION
.P
.I BigFoot 
is a PHP application that supports the rapid
writing and rendering of web-based lecture notes
with auto-numbered
footnotes.
A web page is rendered in a two column frame- text to the left and 
footnotes to the right:
.cB
 .-----.-------.
 |     |       |
 | lhs | rhs   |
 |     |       |
 .-----.-------.     
.cE
.P
Note that the rhs frame is larger than the lhs. This larger frame is used
to switch between displaying multiple big things, while keeping the lhs frame (mostly) constant.
A 
.I screen
style sheet adds large amounts of white space before and after each footnote- so clicking
on a link to a footnote shows one, and only one, footnote in the right hand side frame.
Students can then focus on one footnote at a time (in the rhs frame) while the lhs frame
offers a flow through numerous topics. 
.P
Students can print all the text and footnotes by printing either frame
(a second
.I print
style sheet does not add white space around the footnotes so
the printed notes aren't excessively long).
.SH MOTIVATION
The authoring environments for 
content management systems, wikis, blogging software,
and web-based teaching systems 
are clumsy- 
at least for  creating long complex technical descriptions.
For example, in WordPress or Moodle or various wikis, it is all to easy 
to update the wrong window, then lose all your changes.
Hence, in
.I BigFoot,
content is written in a text editor (e.g. EMACS) and saved to a PHP file.
.SH INSTALLATION
Download
.I http://unbox.org/dust/tags/bigfoot/1.0/bigfoot.zip
and unzip it to an empty, web-readable
directory. 

Add your title into \fCindex.html\fR in the
\fC<title>\fR tag.

Edit the header of \fCtext.php\fR after the following example.
.cB
// top of file
<?
include("notes.inc");
note0("<img align=center src=img/bugs.jpg>"); // define an opening graphic
head("Learning Better IV&V Practices",        // title
       "Tim Menzies",                         // author
       "Lane Dept.  Com. Sci. & Elec.  Eng.", // organization
       "tim@menzies.us",                      // email
       "http://menzies.us",                   // url
       "2007",                                // year of copyright
       "May 1 2007",                          // date
        ""                                    // notes. May be blank.
);
?>
.cE
.SH FUNCTIONS
Within the \fCtext.php\fR file, various PHP functions can be called
in the standard PHP manner; i.e.
.cB
<? function(arg1,arg2,...); ?>
.cE
.P
The following functions should be called only once.
.P
.I head(title, author, org, email, url, year, date, notes);
.RS
Defines the header. Must be called before \fIneck()\fR
.RE
.I note0(imageFile);
.RS
Should be called once, and only once, at start of file.
.RE
.I neck();
.RS
This must be called after all the page one material- see the example in the download file.
.RE
.I toes();
.RS
This must be called on the last line of the \fItext.php\fR file.
.RE
.P
The following functions can be called any number of times
.P
.I note(textString, footnoteString);
.RS
Presents \fItextString\fR on the lhs frame and generated a footnote from \fIfootnoteString\fR.
Returns the number of the new footnote so the idiom \fI$number=note("txt","footnote")\fR
stores the footnote number for later use.
.RE
.I ref($number);
.RS
Adds a link to a previously defined footnote.
.RE
.SH FILES
.I index.html
.RS
Defines the frame sizes.
.RE
.I text.php
.RS
Defines the content of the talk.
.RE
.I bigfoot.inc
.RS
Stores the PHP code for 
.I BigFoot.
.RE
.I img/print.css
.RS
Defines the print styles. Note that a page break is added before each \fI<H1>\fR entry.
.RE
.I img/screen.css
.RS
Defines the on-screen styles. 
Adds large amounts of white space around each footnote so, when shown in the rhs frame, it seems to be a stand alone image.
.RE
.SH BUGS
None known, yet.
.SH AUTHOR
Tim Menzies <tim@menzies.us>
.SH COPYRIGHT
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; version 2.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc.,51 Franklin Street, Fifth Floor, Boston, 
MA 02110-1301, USA.
