.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH BIGFOOT 1 "May 2007" Dust "User Manuals"
.de cB
.ps -2
.ft CB
.in 7
.nf
..
.de cE
.fi
.in  
.ft
.ps
..
.SH NAME
bigfoot
.SH DESCRIPTION
.P
.I Bigfoot 
is a PHP application that supports the rapid
writing and renderring of web-based lecture notes
with auto-numbered
footnotes.
A web page is rendered in a two column frame- text to the left and 
footnotes to the right.
A 
.I screen
style sheet adds large amounts of white space before and after each footnote- so clicking
on a link to a footnote shows one, and only one, footnote in the right hand side frame.
The footnotes can hence be quite large; e.g. a large pdf showing graphs of experimental
results.
A second
.I print
style sheet does not add white space around the footnotes so
the lectures can be quickly printed.
.SH MOTIVATION
The authoring environments for 
content management systems, wikis, blogging software,
and web-based teaching systems 
are clumsy- 
at least for  creating long complex technical descriptions.
For example, in WordPress or Moodle or various wikis, it is all to easy 
to update the wrong window, then lose all your changes.

Hence, in
.I Bigfoot,
content is written in a text editor (e.g. EMACS) and saved to a PHP file.
The file is showm in a two-frame
html page with the top-of-page shown on the left, and the top-of-footnotes
shown on the right.
.cB
 .-----.-----.
 |     |     |
 | lhs | rhs |
 |     |     |
 .-----.-----.     
.cE
Students can print all the text and footnotes by printing either frame.
.SH INSTALLATION
1. Copy an existing 
.I BigFoot
website to a web-accessible directory;

2. Add your title into \fCindex.html\fR in the
\fC<title>\fR tag.

3. Edit the header of \fCtext.php\fR after the following example.

.cB
// top of file
<?
include("notes.inc");
note0("<img align=center src=img/bugs.jpg>"); // define an openning graphic
head("Learning Better IV&V Practices",        // title
       "Tim Menzies",                         // author
       "Lane Dept.  Com. Sci. & Elec.  Eng.", // organization
       "tim@menzies.us",                      // email
       "http://menzies.us",                   // url
       "2007",                                // year of copyright
       "May 1 2007",                          // date
        ""                                    // notes. May be blank.
);
?>
.cE
.SH FUNCTIONS
Within the \fCtext.php\fR file, various PHP functions can be called
in the standard PHP manner; i.e.
.cB
<? function(arg1,arg2,...); ?>
.cE
.P
.IP \fInote0(imageFile)\fR
The above example shows how to use this function.
Should be called once, and only once, at start of file.
.IP "\fInote(textString, footnoteString)\fR"
Use the alternate system wide
.I config-file
instead of
.IR /etc/foo.conf .
This overrides any
.B FOOCONF
environment variable.
.IP -a
In addition to the baz segments, also parse the
blurfl headers.
.IP -r
Recursive mode. Operates as fast as lightning
at the expense of a megabyte of virtual memory.


.B index.html
defines the two frames, and the title.
 
frobnicates the bar library by tweaking internal
symbol tables. By default it parses all baz segments
and rearranges them in reverse order by time for the
.BR xyzzy (1)
linker to find them. The symdef entry is then compressed
using the WBG (Whiz-Bang-Gizmo) algorithm.
All files are processed in the order specified.
.P
.SH OPTIONS
.SH FILES
.I /etc/foo.conf
.RS
The system wide configuration file. See
.BR foo (5)
for further details.
.RE
.I ~/.foorc
.RS
Per user configuration file. See
.BR foo (5)
for further details.
.SH ENVIRONMENT
.IP FOOCONF
If non-null the full pathname for an alternate system wide
.IR foo.conf .
Overridden by the
.B -c
option.
.SH DIAGNOSTICS
The following diagnostics may be issued on stderr:
 
Bad magic number.
.RS
The input file does not look like an archive file.
.RE
Old style baz segments.
.RS
.B foo
can only handle new style baz segments. COBOL
object libraries are not supported in this version.
.SH BUGS
The command name should have been chosen more carefully
to reflect its purpose.
.SH AUTHOR
Tim Menzies <tim@menzies.us>
.SH "SEE ALSO"
.BR bar (1),
.BR foo (5),
.BR xyzzy (1)

